import { expect } from "@jest/globals";
import { readFileSync } from "fs";
import { cwd } from "process";
import { decodeSAMLResponse, validateSAMLResponse } from "./sso";

function readFixture(path) {
  return readFileSync(`${cwd()}/test/fixtures/${path}`).toString("utf-8");
}

describe("decodeSAMLResponse", () => {
  test("decoding valid encoded SAML response", () => {
    // Encoded SAML response. Generated by passing the raw SAML response
    // into https://www.samltool.com/encode.php
    // Note that NextJS handles URL decoding
    const encoded = readFixture("saml_response_encoded.txt");

    // Expected decoded SAML response
    // Pulled from https://www.samltool.com/generic_sso_res.php
    const expected = readFixture("saml_response.xml");

    expect(decodeSAMLResponse(encoded).replace(/\s/g, "")).toEqual(
      expected.replace(/\s/g, "")
    );
  });
});

describe("validateSAMLResponse", () => {
  test("validate successful SAML response", () => {
    // SAML response pulled from https://www.samltool.com/generic_sso_res.php
    const samlResp = readFixture("saml_response.xml");
    const result = validateSAMLResponse(samlResp, "test-certificate");

    expect(result.error).toBeUndefined();
    expect(result.userId).toEqual("1234");
  });

  test("validate wrong cert SAML response", () => {
    const samlResp = readFixture("saml_response_wrong_cert.xml");
    const result = validateSAMLResponse(samlResp, "test-certificate");

    expect(result.error).toEqual("Could verify authenticity of response");
  });

  test("validate bad status SAML response", () => {
    const samlResp = readFixture("saml_response_bad_status.xml");
    const result = validateSAMLResponse(samlResp, "test-certificate");

    expect(result.error).toEqual("Response was not successful");
  });
});
